FROM node:16.13.2-alpine3.14

WORKDIR /app

COPY . ./

# building the app
RUN yarn install

RUN chown -R node: /app
USER node
RUN yarn run build

EXPOSE 3000

# Running the app
CMD [ "yarn", "run", "dev" ]